### ISSUE TITLE
Does not work with PHP version 7.0

### ISSUE THREAD

**Issue by Babinsky** [c5labs/fotorama-block#1]
Hi Oliver
Thanks for your work with the fotorama block. I really like it.
But I think there is a problem with PHP version 7.
I found this comment at the very bottom from Mesuva, which might help you:
http://documentation.concrete5.org/developers/assets/requiring-an-asset
I had all sorts of erros, poking around in the database. Anyway, after setting PHP version back to 5.6 I was able to save my website. But I thought you might like to know.
Regards, B.

**Comment by olsgreen** [comment]
Thanks, I'll take a look.

**Comment by olsgreen** [comment]
Fixed in the latest commit.

**Comment by Babinsky** [comment]
Oliver, thanks very much for your fast reply and fix. Have a good day.
